export { default as Trending } from "./Trending/Trending"
export { default as Search } from "./Search/Search"
export { default as Profile } from "./profile/Profile"
export { default as Favorites } from "./favorites/Favorites"
export { default as Screen404 } from "./system/Screen404"
export { default as Home } from "./home/Home"
export { default as Admin } from "./admin/home/Admin"
export { default as Auth } from "./auth/Auth"
