export { default as Trending } from './trending/Trending'
export { default as Search } from './Search/Search'
export { default as Profile } from './profile/Profile'
export { default as Favorites } from './favorites/Favorites'
export { default as Genre } from './genre/Genre'
export { default as Screen404 } from './system/Screen404'
export { default as Home } from './home/Home'
export { default as Movie } from './movie/Movie'
export { default as Actor } from './actor/Actor'
export { default as Auth } from './auth/Auth'

